query GetClosetData($id: String!) {
  rats(where: { owner: { _eq: $id } }) {
    id
    name
    image
    accessory
    background
    color
    ears
    eyes
    generation
    glasses
    hand
    hat
    head
    markings
    pet
    shirt
    snout
    tail
    torso
    type
    cunning
    cuteness
    rattitude
  }

  closet_pieces(
    where: {
      _or: [
        { active: { _eq: true } }
        { closet_tokens: { owner: { _eq: $id } } }
      ]
    }
  ) {
    id
    image
    active
    name
    cost
    max_tokens
    max_per_wallet
    collection
    description
    piece_type
    sponsor
    sponsor_url
    owned: closet_tokens_aggregate(where: { owner: { _eq: $id } }) {
      aggregate {
        count
      }
    }
    minted: closet_tokens_aggregate {
      aggregate {
        sum {
          amount
        }
      }
    }
  }
}
