query getSurveyById(
  $id: Int!
  $includeResponses: Boolean = false
  $includeMyResponses: Boolean = false
  $wallet: String
) {
  surveys_by_pk(id: $id) {
    id
    title
    description
    is_active
    is_public
    max_responses
    response_count @include(if: $includeResponses)
    latest_response @include(if: $includeResponses)
    contract {
      address
      token_type
      chain
    }
    callerResponses: survey_responses(where: { wallet: { _eq: $wallet } })
      @include(if: $includeMyResponses) {
      wallet
      response_values
      question_ids
    }
    survey_responses @include(if: $includeResponses) {
      wallet
      response_values
      question_ids
      created_at
    }
    questions(order_by: { id: asc }) {
      id
      prompt
      is_required
    }
  }
}
