query getSurveyById(
  $id: Int!
  $includeResponses: Boolean = false
  $includeMyResponses: Boolean = false
  $wallet: String
) {
  surveys_by_pk(id: $id) {
    id
    title
    description
    is_active
    is_public
    max_responses
    owner
    response_count
    latest_response @include(if: $includeResponses)
    contract {
      address
      token_type
      chain
    }
    callerResponses: survey_responses(where: { wallet: { _eq: $wallet } })
      @include(if: $includeMyResponses) {
      wallet
      question_responses
    }
    survey_responses @include(if: $includeResponses) {
      wallet
      question_responses
      created_at
      token_count
    }
    questions(order_by: { id: asc }) {
      id
      prompt
      is_required
      question_type
      options {
        id
        content
      }
    }
  }
}
